<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Pottmayer.Pandora.Modules.Channels.Abstractions/Pottmayer.Pandora.Modules.Channels.Abstractions.csproj" />
    <ProjectReference Include="../Pottmayer.Pandora.Modules.Channels.Domain/Pottmayer.Pandora.Modules.Channels.Domain.csproj" />
    <ProjectReference Include="../../../Shared/Pottmayer.Pandora.Shared.Persistence/Pottmayer.Pandora.Shared.Persistence.csproj" />
    <!-- Tars: Data -->
    <PackageReference Include="Pottmayer.Tars.Data.Relational" Version="0.0.8" />
    <PackageReference Include="Pottmayer.Tars.Messaging.EntityFrameworkCore" Version="0.0.8" />
  </ItemGroup>

</Project>
