<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Pottmayer.Pandora.Modules.Integrations.Abstractions/Pottmayer.Pandora.Modules.Integrations.Abstractions.csproj" />
    <ProjectReference Include="../Pottmayer.Pandora.Modules.Integrations.Contracts/Pottmayer.Pandora.Modules.Integrations.Contracts.csproj" />
    <ProjectReference Include="../Pottmayer.Pandora.Modules.Integrations.Domain/Pottmayer.Pandora.Modules.Integrations.Domain.csproj" />
    <!-- Tars: DataProtection (ISecretProtector) -->
    <PackageReference Include="Pottmayer.Tars.Security.DataProtection.Abstractions" Version="0.0.8" />
    <!-- Tars: Core -->
    <PackageReference Include="Pottmayer.Tars.Core.Cqrs" Version="0.0.8" />
    <PackageReference Include="Pottmayer.Tars.Core.Mediator" Version="0.0.8" />
    <!-- Tars: Data -->
    <PackageReference Include="Pottmayer.Tars.Data.Abstractions" Version="0.0.8" />
    <!-- Tars: Messaging -->
    <PackageReference Include="Pottmayer.Tars.Messaging" Version="0.0.8" />
  </ItemGroup>

</Project>
